name: Style

on:
  pull_request: {}
  push:
    branches:
      - main
      - dev

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: setup python, poetry, and just
        uses: ./.github/actions/setup_python_poetry_just
        with:
          poetry_cache_counter: 0  # increment to rebuild poetry cache

      - name: install dependencies
        uses: ./.github/actions/install_dependencies

      - name: lint
        run: just lint