
name: Style

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: python style check
        uses: weibullguy/python-lint-plus@master
        with:
          python-root-list: "."
          use-black: true
          use-yapf: false
          use-isort: false
          use-docformatter: false
          use-pycodestyle: false
          use-autopep8: false
          use-pydocstyle: true
          use-mypy: false
          use-pylint: false
          use-flake8: true
          use-mccabe: false
          use-radon: false
          use-rstcheck: false
          use-check-manifest: false
          use-pyroma: false